version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    networks:
      - washify

  client:
    build: ./client
    ports:
      - "3000:4173"
    env_file:
      - ./client/.env
    depends_on:
      - server
    networks:
      - washify

networks:
  washify:
    driver: bridge